catalogue:
	@bash components/catalogue.sh
	
mongodb:
	@bash components/mongodb.sh
	
cart:
	@bash components/cart.sh
	
user:
	@bash components/user.sh
	
mysql:
	@bash components/mysql.sh
	
rabbitmq:
	@bash components/rabbitmq.sh
	
redis:
	@bash components/redis.sh
	
payment:
	@bash components/payment.sh
	
shipping:
	@bash components/shipping.sh
	
frontend:
	@bash components/frontend.sh	